# Generated by Django 5.0.2 on 2024-02-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeexercise',
            name='video',
        ),
        migrations.RemoveField(
            model_name='questionexercise',
            name='video',
        ),
        migrations.AddField(
            model_name='codeexercise',
            name='code_name',
            field=models.CharField(default='Codigo de ejercicio', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='code_exercises',
            field=models.ManyToManyField(blank=True, related_name='videos', to='Course_app.codeexercise'),
        ),
        migrations.AddField(
            model_name='video',
            name='question_exercises',
            field=models.ManyToManyField(blank=True, related_name='videos', to='Course_app.questionexercise'),
        ),
    ]
