# Generated by Django 5.0.2 on 2024-03-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0009_remove_video_code_exercises_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionexercise',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='questionexercise',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='questionexercise',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='questionexercise',
            name='option_d',
        ),
        migrations.AddField(
            model_name='questionexercise',
            name='option_1',
            field=models.FileField(null=True, upload_to='question_video_1/'),
        ),
        migrations.AddField(
            model_name='questionexercise',
            name='option_2',
            field=models.FileField(null=True, upload_to='question_video_2/'),
        ),
        migrations.AddField(
            model_name='questionexercise',
            name='option_3',
            field=models.FileField(null=True, upload_to='question_video_3/'),
        ),
        migrations.AddField(
            model_name='questionexercise',
            name='option_4',
            field=models.FileField(null=True, upload_to='question_video_4/'),
        ),
        migrations.AddField(
            model_name='video',
            name='image_file',
            field=models.FileField(null=True, upload_to='video_images/'),
        ),
        migrations.AlterField(
            model_name='questionexercise',
            name='correct_answer',
            field=models.IntegerField(),
        ),
    ]
