# Generated by Django 5.0.2 on 2024-03-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0010_remove_questionexercise_option_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionexercise',
            name='video',
        ),
        migrations.DeleteModel(
            name='CodeExercise',
        ),
        migrations.DeleteModel(
            name='QuestionExercise',
        ),
    ]
